"""The audit hash chain (FR-AUD-05), and a reason long enough to be one.

Three changes to `audit_event`.

A sequence, because the chain needs a total order and two events can share a
microsecond. It is allocated while the writer holds the chain lock, so allocation
order and link order are the same thing, and it is unique because two events
sharing a position would make the order the verifier walks ambiguous — precisely
where a row could be hidden.

`prev_hash` and `hash`, stored rather than derived on read. That is the point: a
verifier compares what was written against what the content now hashes to, and a
value computed on read would agree with a tampered row by construction.

`reason` widened from 64 to 512. FR-ADM-07 asks for a justification in the
actor's own words, and 64 characters is a fragment. The failure this avoids is
particularly bad: audit writes never raise, so an over-length reason would have
lost the whole event silently.

Existing rows are sealed in place, in `occurred_at` then `id` order. The
alternative — leaving them unchained and starting from the next write — would
mean the verifier needs a rule about where the chain begins, and a rule about
where a chain begins is a place to hide a row.

**This migration is not safe to run while an older broker is still writing.**
The new columns are NOT NULL, so an instance built before this revision inserts
rows the table rejects — and audit writes are deliberately swallowed, so those
events are lost silently rather than loudly. Deploy the code first, then migrate,
or take the writers down for the migration. It is a short window and an easy one
to miss, which is why it is written down here rather than in a runbook.

Revision ID: 0014_audit_hash_chain
Revises: 0013_mfa_recovery_code
Created: 2026-09-11
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from campusid.audit.chain import GENESIS, link

revision: str = "0014_audit_hash_chain"
down_revision: str | None = "0013_mfa_recovery_code"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SEALED_COLUMNS: Sequence[str] = (
    "id",
    "event_id",
    "event_type",
    "outcome",
    "occurred_at",
    "correlation_id",
    "actor",
    "subject",
    "target",
    "reason",
    "source_ip",
    "user_agent",
    "session_id",
    "detail",
)


def upgrade() -> None:
    op.alter_column(
        "audit_event",
        "reason",
        type_=sa.String(length=512),
        existing_type=sa.String(length=64),
        existing_nullable=True,
    )

    # Added nullable, backfilled, then made NOT NULL. Adding them NOT NULL with a
    # default would put the same placeholder hash on every existing row, which is
    # a chain that verifies as broken everywhere rather than one that is correct.
    op.add_column("audit_event", sa.Column("seq", sa.BigInteger(), nullable=True))
    op.add_column("audit_event", sa.Column("prev_hash", sa.String(length=64), nullable=True))
    op.add_column("audit_event", sa.Column("hash", sa.String(length=64), nullable=True))

    _seal_existing_rows()

    op.alter_column("audit_event", "seq", nullable=False)
    op.alter_column("audit_event", "prev_hash", nullable=False)
    op.alter_column("audit_event", "hash", nullable=False)

    # An identity column rather than a serial, so the sequence is owned by the
    # table and cannot be left behind by a later rename.
    op.execute("ALTER TABLE audit_event ALTER COLUMN seq ADD GENERATED BY DEFAULT AS IDENTITY")
    op.execute(
        "SELECT setval(pg_get_serial_sequence('audit_event', 'seq'), "
        "COALESCE((SELECT MAX(seq) FROM audit_event), 0) + 1, false)"
    )

    op.create_index("uq_audit_event_seq", "audit_event", ["seq"], unique=True)


def _seal_existing_rows() -> None:
    """Chain whatever is already in the table, oldest first.

    Ordered by `occurred_at` then `id`, which is the only order the existing rows
    carry — the sequence being created here does not exist yet for them. Ties on
    the timestamp are broken by the primary key so the result is deterministic
    rather than whatever the planner returns.
    """
    bind = op.get_bind()
    columns = ", ".join(SEALED_COLUMNS)
    rows = bind.execute(
        sa.text(f"SELECT {columns} FROM audit_event ORDER BY occurred_at, id")  # noqa: S608
    ).mappings()

    previous = GENESIS
    for position, row in enumerate(rows, start=1):
        event = dict(row)
        current = link(previous, event)
        bind.execute(
            sa.text(
                "UPDATE audit_event SET seq = :seq, prev_hash = :prev, hash = :hash "
                "WHERE id = :id"
            ),
            {"seq": position, "prev": previous, "hash": current, "id": event["id"]},
        )
        previous = current


def downgrade() -> None:
    raise NotImplementedError("CampusID migrations are forward-only")
